title: oquintaninha
email: 
description: Written and Directed by
author: VinÃ­cius Knecht
domain: "oquintaninha.github.io"
url: "https://oquintaninha.github.io"
baseurl: ""
instagram_username: oquintaninha

# Build settings
theme: minima
plugins:
  - jekyll-feed
