title: VINÃCIUS KNECHT
email: vknecht@gmail.com
description: poet.
domain: "oquintaninha.github.io"
url: "https://oquintaninha.github.io"
baseurl: ""
instagram_username: @oquintaninha
# github_username:  oquintaninha

# Build settings
theme: minima
plugins:
  - jekyll-feed
